// Generated by https://quicktype.io

export interface PostProductResponse {
    success:   boolean;
    itemFound: boolean;
    item:      Item;
}

export interface Item {
    id:           string;
    name:         string;
    secret:       string;
    active:       number;
    regUserId:    number;
    regDate:      string;
    regDatetime:  string;
    regTimestamp: number;
}
